// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hq/pet/v1/pet.proto

package petv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetMood int32

const (
	PetMood_PET_MOOD_UNSPECIFIED PetMood = 0
	PetMood_PET_MOOD_IDLE        PetMood = 1
	PetMood_PET_MOOD_HAPPY       PetMood = 2
	PetMood_PET_MOOD_HUNGRY      PetMood = 3
	PetMood_PET_MOOD_SAD         PetMood = 4
	PetMood_PET_MOOD_SLEEPING    PetMood = 5
)

// Enum value maps for PetMood.
var (
	PetMood_name = map[int32]string{
		0: "PET_MOOD_UNSPECIFIED",
		1: "PET_MOOD_IDLE",
		2: "PET_MOOD_HAPPY",
		3: "PET_MOOD_HUNGRY",
		4: "PET_MOOD_SAD",
		5: "PET_MOOD_SLEEPING",
	}
	PetMood_value = map[string]int32{
		"PET_MOOD_UNSPECIFIED": 0,
		"PET_MOOD_IDLE":        1,
		"PET_MOOD_HAPPY":       2,
		"PET_MOOD_HUNGRY":      3,
		"PET_MOOD_SAD":         4,
		"PET_MOOD_SLEEPING":    5,
	}
)

func (x PetMood) Enum() *PetMood {
	p := new(PetMood)
	*p = x
	return p
}

func (x PetMood) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetMood) Descriptor() protoreflect.EnumDescriptor {
	return file_hq_pet_v1_pet_proto_enumTypes[0].Descriptor()
}

func (PetMood) Type() protoreflect.EnumType {
	return &file_hq_pet_v1_pet_proto_enumTypes[0]
}

func (x PetMood) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PetMood.Descriptor instead.
func (PetMood) EnumDescriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{0}
}

type PetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hunger        int32                  `protobuf:"varint,1,opt,name=hunger,proto3" json:"hunger,omitempty"`
	Happiness     int32                  `protobuf:"varint,2,opt,name=happiness,proto3" json:"happiness,omitempty"`
	Energy        int32                  `protobuf:"varint,3,opt,name=energy,proto3" json:"energy,omitempty"`
	Sleeping      bool                   `protobuf:"varint,4,opt,name=sleeping,proto3" json:"sleeping,omitempty"`
	Mood          PetMood                `protobuf:"varint,5,opt,name=mood,proto3,enum=hq.pet.v1.PetMood" json:"mood,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastDecayAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_decay_at,json=lastDecayAt,proto3" json:"last_decay_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetState) Reset() {
	*x = PetState{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetState) ProtoMessage() {}

func (x *PetState) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetState.ProtoReflect.Descriptor instead.
func (*PetState) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{0}
}

func (x *PetState) GetHunger() int32 {
	if x != nil {
		return x.Hunger
	}
	return 0
}

func (x *PetState) GetHappiness() int32 {
	if x != nil {
		return x.Happiness
	}
	return 0
}

func (x *PetState) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *PetState) GetSleeping() bool {
	if x != nil {
		return x.Sleeping
	}
	return false
}

func (x *PetState) GetMood() PetMood {
	if x != nil {
		return x.Mood
	}
	return PetMood_PET_MOOD_UNSPECIFIED
}

func (x *PetState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PetState) GetLastDecayAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDecayAt
	}
	return nil
}

type PetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Cookies       int32                  `protobuf:"varint,3,opt,name=cookies,proto3" json:"cookies,omitempty"`
	PetState      *PetState              `protobuf:"bytes,4,opt,name=pet_state,json=petState,proto3" json:"pet_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStateResponse) Reset() {
	*x = PetStateResponse{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStateResponse) ProtoMessage() {}

func (x *PetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStateResponse.ProtoReflect.Descriptor instead.
func (*PetStateResponse) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{1}
}

func (x *PetStateResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PetStateResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PetStateResponse) GetCookies() int32 {
	if x != nil {
		return x.Cookies
	}
	return 0
}

func (x *PetStateResponse) GetPetState() *PetState {
	if x != nil {
		return x.PetState
	}
	return nil
}

type GetPetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetStateRequest) Reset() {
	*x = GetPetStateRequest{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetStateRequest) ProtoMessage() {}

func (x *GetPetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetStateRequest.ProtoReflect.Descriptor instead.
func (*GetPetStateRequest) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{2}
}

type FeedPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedPetRequest) Reset() {
	*x = FeedPetRequest{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPetRequest) ProtoMessage() {}

func (x *FeedPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPetRequest.ProtoReflect.Descriptor instead.
func (*FeedPetRequest) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{3}
}

type PlayWithPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayWithPetRequest) Reset() {
	*x = PlayWithPetRequest{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayWithPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayWithPetRequest) ProtoMessage() {}

func (x *PlayWithPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayWithPetRequest.ProtoReflect.Descriptor instead.
func (*PlayWithPetRequest) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{4}
}

type PutPetToSleepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPetToSleepRequest) Reset() {
	*x = PutPetToSleepRequest{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPetToSleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPetToSleepRequest) ProtoMessage() {}

func (x *PutPetToSleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPetToSleepRequest.ProtoReflect.Descriptor instead.
func (*PutPetToSleepRequest) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{5}
}

type WakePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakePetRequest) Reset() {
	*x = WakePetRequest{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakePetRequest) ProtoMessage() {}

func (x *WakePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakePetRequest.ProtoReflect.Descriptor instead.
func (*WakePetRequest) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{6}
}

type WatchPetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPetStateRequest) Reset() {
	*x = WatchPetStateRequest{}
	mi := &file_hq_pet_v1_pet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPetStateRequest) ProtoMessage() {}

func (x *WatchPetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hq_pet_v1_pet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPetStateRequest.ProtoReflect.Descriptor instead.
func (*WatchPetStateRequest) Descriptor() ([]byte, []int) {
	return file_hq_pet_v1_pet_proto_rawDescGZIP(), []int{7}
}

var File_hq_pet_v1_pet_proto protoreflect.FileDescriptor

const file_hq_pet_v1_pet_proto_rawDesc = "" +
	"\n" +
	"\x13hq/pet/v1/pet.proto\x12\thq.pet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\bPetState\x12\x16\n" +
	"\x06hunger\x18\x01 \x01(\x05R\x06hunger\x12\x1c\n" +
	"\thappiness\x18\x02 \x01(\x05R\thappiness\x12\x16\n" +
	"\x06energy\x18\x03 \x01(\x05R\x06energy\x12\x1a\n" +
	"\bsleeping\x18\x04 \x01(\bR\bsleeping\x12&\n" +
	"\x04mood\x18\x05 \x01(\x0e2\x12.hq.pet.v1.PetMoodR\x04mood\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rlast_decay_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastDecayAt\"\x9a\x01\n" +
	"\x10PetStateResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\acookies\x18\x03 \x01(\x05R\acookies\x120\n" +
	"\tpet_state\x18\x04 \x01(\v2\x13.hq.pet.v1.PetStateR\bpetState\"\x14\n" +
	"\x12GetPetStateRequest\"\x10\n" +
	"\x0eFeedPetRequest\"\x14\n" +
	"\x12PlayWithPetRequest\"\x16\n" +
	"\x14PutPetToSleepRequest\"\x10\n" +
	"\x0eWakePetRequest\"\x16\n" +
	"\x14WatchPetStateRequest*\x88\x01\n" +
	"\aPetMood\x12\x18\n" +
	"\x14PET_MOOD_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPET_MOOD_IDLE\x10\x01\x12\x12\n" +
	"\x0ePET_MOOD_HAPPY\x10\x02\x12\x13\n" +
	"\x0fPET_MOOD_HUNGRY\x10\x03\x12\x10\n" +
	"\fPET_MOOD_SAD\x10\x04\x12\x15\n" +
	"\x11PET_MOOD_SLEEPING\x10\x052\xc8\x03\n" +
	"\n" +
	"PetService\x12I\n" +
	"\vGetPetState\x12\x1d.hq.pet.v1.GetPetStateRequest\x1a\x1b.hq.pet.v1.PetStateResponse\x12A\n" +
	"\aFeedPet\x12\x19.hq.pet.v1.FeedPetRequest\x1a\x1b.hq.pet.v1.PetStateResponse\x12I\n" +
	"\vPlayWithPet\x12\x1d.hq.pet.v1.PlayWithPetRequest\x1a\x1b.hq.pet.v1.PetStateResponse\x12M\n" +
	"\rPutPetToSleep\x12\x1f.hq.pet.v1.PutPetToSleepRequest\x1a\x1b.hq.pet.v1.PetStateResponse\x12A\n" +
	"\aWakePet\x12\x19.hq.pet.v1.WakePetRequest\x1a\x1b.hq.pet.v1.PetStateResponse\x12O\n" +
	"\rWatchPetState\x12\x1f.hq.pet.v1.WatchPetStateRequest\x1a\x1b.hq.pet.v1.PetStateResponse0\x01B\x1aZ\x18hq/proto/hq/pet/v1;petv1b\x06proto3"

var (
	file_hq_pet_v1_pet_proto_rawDescOnce sync.Once
	file_hq_pet_v1_pet_proto_rawDescData []byte
)

func file_hq_pet_v1_pet_proto_rawDescGZIP() []byte {
	file_hq_pet_v1_pet_proto_rawDescOnce.Do(func() {
		file_hq_pet_v1_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hq_pet_v1_pet_proto_rawDesc), len(file_hq_pet_v1_pet_proto_rawDesc)))
	})
	return file_hq_pet_v1_pet_proto_rawDescData
}

var file_hq_pet_v1_pet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hq_pet_v1_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hq_pet_v1_pet_proto_goTypes = []any{
	(PetMood)(0),                  // 0: hq.pet.v1.PetMood
	(*PetState)(nil),              // 1: hq.pet.v1.PetState
	(*PetStateResponse)(nil),      // 2: hq.pet.v1.PetStateResponse
	(*GetPetStateRequest)(nil),    // 3: hq.pet.v1.GetPetStateRequest
	(*FeedPetRequest)(nil),        // 4: hq.pet.v1.FeedPetRequest
	(*PlayWithPetRequest)(nil),    // 5: hq.pet.v1.PlayWithPetRequest
	(*PutPetToSleepRequest)(nil),  // 6: hq.pet.v1.PutPetToSleepRequest
	(*WakePetRequest)(nil),        // 7: hq.pet.v1.WakePetRequest
	(*WatchPetStateRequest)(nil),  // 8: hq.pet.v1.WatchPetStateRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_hq_pet_v1_pet_proto_depIdxs = []int32{
	0,  // 0: hq.pet.v1.PetState.mood:type_name -> hq.pet.v1.PetMood
	9,  // 1: hq.pet.v1.PetState.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: hq.pet.v1.PetState.last_decay_at:type_name -> google.protobuf.Timestamp
	1,  // 3: hq.pet.v1.PetStateResponse.pet_state:type_name -> hq.pet.v1.PetState
	3,  // 4: hq.pet.v1.PetService.GetPetState:input_type -> hq.pet.v1.GetPetStateRequest
	4,  // 5: hq.pet.v1.PetService.FeedPet:input_type -> hq.pet.v1.FeedPetRequest
	5,  // 6: hq.pet.v1.PetService.PlayWithPet:input_type -> hq.pet.v1.PlayWithPetRequest
	6,  // 7: hq.pet.v1.PetService.PutPetToSleep:input_type -> hq.pet.v1.PutPetToSleepRequest
	7,  // 8: hq.pet.v1.PetService.WakePet:input_type -> hq.pet.v1.WakePetRequest
	8,  // 9: hq.pet.v1.PetService.WatchPetState:input_type -> hq.pet.v1.WatchPetStateRequest
	2,  // 10: hq.pet.v1.PetService.GetPetState:output_type -> hq.pet.v1.PetStateResponse
	2,  // 11: hq.pet.v1.PetService.FeedPet:output_type -> hq.pet.v1.PetStateResponse
	2,  // 12: hq.pet.v1.PetService.PlayWithPet:output_type -> hq.pet.v1.PetStateResponse
	2,  // 13: hq.pet.v1.PetService.PutPetToSleep:output_type -> hq.pet.v1.PetStateResponse
	2,  // 14: hq.pet.v1.PetService.WakePet:output_type -> hq.pet.v1.PetStateResponse
	2,  // 15: hq.pet.v1.PetService.WatchPetState:output_type -> hq.pet.v1.PetStateResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hq_pet_v1_pet_proto_init() }
func file_hq_pet_v1_pet_proto_init() {
	if File_hq_pet_v1_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hq_pet_v1_pet_proto_rawDesc), len(file_hq_pet_v1_pet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hq_pet_v1_pet_proto_goTypes,
		DependencyIndexes: file_hq_pet_v1_pet_proto_depIdxs,
		EnumInfos:         file_hq_pet_v1_pet_proto_enumTypes,
		MessageInfos:      file_hq_pet_v1_pet_proto_msgTypes,
	}.Build()
	File_hq_pet_v1_pet_proto = out.File
	file_hq_pet_v1_pet_proto_goTypes = nil
	file_hq_pet_v1_pet_proto_depIdxs = nil
}
