truncate table assignment restart identity cascade;

insert into assignment (category, prompt, expected_answer) values
  ('SCIENCE', 'What do plants need from the sun to grow?', 'Light'),
  ('SCIENCE', 'What part of a plant takes in water from the soil?', 'Roots'),
  ('SCIENCE', 'What do we call water when it freezes?', 'Ice'),
  ('SCIENCE', 'What sense do you use with your ears?', 'Hearing'),
  ('SCIENCE', 'What planet do we live on?', 'Earth'),
  ('SCIENCE', 'What animal group has feathers and lays eggs?', 'Birds'),
  ('SCIENCE', 'What is the force that pulls things down to the ground?', 'Gravity'),
  ('SCIENCE', 'What do people breathe in that helps us live?', 'Oxygen'),
  ('SCIENCE', 'What season comes after winter?', 'Spring'),
  ('SCIENCE', 'What do you call an animal that eats plants?', 'Herbivore'),
  ('SCIENCE', 'What is the young form of a frog called?', 'Tadpole'),
  ('SCIENCE', 'What tool can make tiny things look bigger?', 'Microscope'),
  ('SCIENCE', 'What is the center of our solar system?', 'The sun'),
  ('SCIENCE', 'What do bees collect from flowers?', 'Nectar'),
  ('SCIENCE', 'What part of your body pumps blood?', 'Heart'),
  ('SCIENCE', 'What kind of weather has water drops falling from clouds?', 'Rain'),
  ('SCIENCE', 'What gas do plants take in from the air?', 'Carbon dioxide'),
  ('SCIENCE', 'What do we call a place where an animal lives?', 'Habitat'),
  ('SCIENCE', 'What is made when red and blue paint are mixed?', 'Purple'),
  ('SCIENCE', 'What do magnets stick to best?', 'Metal'),
  ('MATH', 'What is 7 + 5?', '12'),
  ('MATH', 'What is 14 - 6?', '8'),
  ('MATH', 'What is 3 + 9?', '12'),
  ('MATH', 'What is 20 - 7?', '13'),
  ('MATH', 'What number comes after 49?', '50'),
  ('MATH', 'What number comes before 30?', '29'),
  ('MATH', 'What is 5 + 5 + 5?', '15'),
  ('MATH', 'How many sides does a triangle have?', '3'),
  ('MATH', 'How many sides does a square have?', '4'),
  ('MATH', 'What is 10 more than 25?', '35'),
  ('MATH', 'What is 10 less than 64?', '54'),
  ('MATH', 'What is 8 + 8?', '16'),
  ('MATH', 'What is 18 - 9?', '9'),
  ('MATH', 'If you have 2 groups of 4 apples, how many apples do you have?', '8'),
  ('MATH', 'What is half of 10?', '5'),
  ('MATH', 'How many pennies make one nickel?', '5'),
  ('MATH', 'How many dimes make one dollar?', '10'),
  ('MATH', 'What is 6 + 7?', '13'),
  ('MATH', 'What is 15 - 8?', '7'),
  ('MATH', 'What number is shown by 4 tens and 2 ones?', '42'),
  ('READING', 'What do we call the person or animal a story is mostly about?', 'Main character'),
  ('READING', 'What is the name for where and when a story happens?', 'Setting'),
  ('READING', 'What punctuation mark ends a question?', 'Question mark'),
  ('READING', 'What punctuation mark ends an excited sentence?', 'Exclamation point'),
  ('READING', 'What do we call a word that means the opposite of another word?', 'Antonym'),
  ('READING', 'What do we call a word that means the same or almost the same as another word?', 'Synonym'),
  ('READING', 'What is the plural of cat?', 'Cats'),
  ('READING', 'What is the plural of box?', 'Boxes'),
  ('READING', 'In the sentence "The dog ran fast," who ran?', 'The dog'),
  ('READING', 'In the sentence "Mia ate an apple," what did Mia eat?', 'An apple'),
  ('READING', 'What is the beginning sound in the word fish?', 'F'),
  ('READING', 'What is the ending sound in the word map?', 'P'),
  ('READING', 'What vowel is in the middle of the word hat?', 'A'),
  ('READING', 'What do we call a made-up story?', 'Fiction'),
  ('READING', 'What do we call a book that gives true facts?', 'Nonfiction'),
  ('READING', 'What is the past tense of jump?', 'Jumped'),
  ('READING', 'What is the past tense of play?', 'Played'),
  ('READING', 'What compound word is made from sun and shine?', 'Sunshine'),
  ('READING', 'What compound word is made from rain and bow?', 'Rainbow'),
  ('READING', 'What do we call the lesson or message of a story?', 'Moral');
