// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: hq/pet/v1/pet.proto

package petv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hq/proto/hq/pet/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PetServiceName is the fully-qualified name of the PetService service.
	PetServiceName = "hq.pet.v1.PetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PetServiceGetPetStateProcedure is the fully-qualified name of the PetService's GetPetState RPC.
	PetServiceGetPetStateProcedure = "/hq.pet.v1.PetService/GetPetState"
	// PetServiceFeedPetProcedure is the fully-qualified name of the PetService's FeedPet RPC.
	PetServiceFeedPetProcedure = "/hq.pet.v1.PetService/FeedPet"
	// PetServicePlayWithPetProcedure is the fully-qualified name of the PetService's PlayWithPet RPC.
	PetServicePlayWithPetProcedure = "/hq.pet.v1.PetService/PlayWithPet"
	// PetServiceApplyGameResultProcedure is the fully-qualified name of the PetService's
	// ApplyGameResult RPC.
	PetServiceApplyGameResultProcedure = "/hq.pet.v1.PetService/ApplyGameResult"
	// PetServicePutPetToSleepProcedure is the fully-qualified name of the PetService's PutPetToSleep
	// RPC.
	PetServicePutPetToSleepProcedure = "/hq.pet.v1.PetService/PutPetToSleep"
	// PetServiceWakePetProcedure is the fully-qualified name of the PetService's WakePet RPC.
	PetServiceWakePetProcedure = "/hq.pet.v1.PetService/WakePet"
	// PetServiceWatchPetStateProcedure is the fully-qualified name of the PetService's WatchPetState
	// RPC.
	PetServiceWatchPetStateProcedure = "/hq.pet.v1.PetService/WatchPetState"
)

// PetServiceClient is a client for the hq.pet.v1.PetService service.
type PetServiceClient interface {
	GetPetState(context.Context, *connect.Request[v1.GetPetStateRequest]) (*connect.Response[v1.PetStateResponse], error)
	FeedPet(context.Context, *connect.Request[v1.FeedPetRequest]) (*connect.Response[v1.PetStateResponse], error)
	PlayWithPet(context.Context, *connect.Request[v1.PlayWithPetRequest]) (*connect.Response[v1.PetStateResponse], error)
	ApplyGameResult(context.Context, *connect.Request[v1.ApplyGameResultRequest]) (*connect.Response[v1.PetStateResponse], error)
	PutPetToSleep(context.Context, *connect.Request[v1.PutPetToSleepRequest]) (*connect.Response[v1.PetStateResponse], error)
	WakePet(context.Context, *connect.Request[v1.WakePetRequest]) (*connect.Response[v1.PetStateResponse], error)
	WatchPetState(context.Context, *connect.Request[v1.WatchPetStateRequest]) (*connect.ServerStreamForClient[v1.PetStateResponse], error)
}

// NewPetServiceClient constructs a client for the hq.pet.v1.PetService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	petServiceMethods := v1.File_hq_pet_v1_pet_proto.Services().ByName("PetService").Methods()
	return &petServiceClient{
		getPetState: connect.NewClient[v1.GetPetStateRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServiceGetPetStateProcedure,
			connect.WithSchema(petServiceMethods.ByName("GetPetState")),
			connect.WithClientOptions(opts...),
		),
		feedPet: connect.NewClient[v1.FeedPetRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServiceFeedPetProcedure,
			connect.WithSchema(petServiceMethods.ByName("FeedPet")),
			connect.WithClientOptions(opts...),
		),
		playWithPet: connect.NewClient[v1.PlayWithPetRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServicePlayWithPetProcedure,
			connect.WithSchema(petServiceMethods.ByName("PlayWithPet")),
			connect.WithClientOptions(opts...),
		),
		applyGameResult: connect.NewClient[v1.ApplyGameResultRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServiceApplyGameResultProcedure,
			connect.WithSchema(petServiceMethods.ByName("ApplyGameResult")),
			connect.WithClientOptions(opts...),
		),
		putPetToSleep: connect.NewClient[v1.PutPetToSleepRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServicePutPetToSleepProcedure,
			connect.WithSchema(petServiceMethods.ByName("PutPetToSleep")),
			connect.WithClientOptions(opts...),
		),
		wakePet: connect.NewClient[v1.WakePetRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServiceWakePetProcedure,
			connect.WithSchema(petServiceMethods.ByName("WakePet")),
			connect.WithClientOptions(opts...),
		),
		watchPetState: connect.NewClient[v1.WatchPetStateRequest, v1.PetStateResponse](
			httpClient,
			baseURL+PetServiceWatchPetStateProcedure,
			connect.WithSchema(petServiceMethods.ByName("WatchPetState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// petServiceClient implements PetServiceClient.
type petServiceClient struct {
	getPetState     *connect.Client[v1.GetPetStateRequest, v1.PetStateResponse]
	feedPet         *connect.Client[v1.FeedPetRequest, v1.PetStateResponse]
	playWithPet     *connect.Client[v1.PlayWithPetRequest, v1.PetStateResponse]
	applyGameResult *connect.Client[v1.ApplyGameResultRequest, v1.PetStateResponse]
	putPetToSleep   *connect.Client[v1.PutPetToSleepRequest, v1.PetStateResponse]
	wakePet         *connect.Client[v1.WakePetRequest, v1.PetStateResponse]
	watchPetState   *connect.Client[v1.WatchPetStateRequest, v1.PetStateResponse]
}

// GetPetState calls hq.pet.v1.PetService.GetPetState.
func (c *petServiceClient) GetPetState(ctx context.Context, req *connect.Request[v1.GetPetStateRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return c.getPetState.CallUnary(ctx, req)
}

// FeedPet calls hq.pet.v1.PetService.FeedPet.
func (c *petServiceClient) FeedPet(ctx context.Context, req *connect.Request[v1.FeedPetRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return c.feedPet.CallUnary(ctx, req)
}

// PlayWithPet calls hq.pet.v1.PetService.PlayWithPet.
func (c *petServiceClient) PlayWithPet(ctx context.Context, req *connect.Request[v1.PlayWithPetRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return c.playWithPet.CallUnary(ctx, req)
}

// ApplyGameResult calls hq.pet.v1.PetService.ApplyGameResult.
func (c *petServiceClient) ApplyGameResult(ctx context.Context, req *connect.Request[v1.ApplyGameResultRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return c.applyGameResult.CallUnary(ctx, req)
}

// PutPetToSleep calls hq.pet.v1.PetService.PutPetToSleep.
func (c *petServiceClient) PutPetToSleep(ctx context.Context, req *connect.Request[v1.PutPetToSleepRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return c.putPetToSleep.CallUnary(ctx, req)
}

// WakePet calls hq.pet.v1.PetService.WakePet.
func (c *petServiceClient) WakePet(ctx context.Context, req *connect.Request[v1.WakePetRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return c.wakePet.CallUnary(ctx, req)
}

// WatchPetState calls hq.pet.v1.PetService.WatchPetState.
func (c *petServiceClient) WatchPetState(ctx context.Context, req *connect.Request[v1.WatchPetStateRequest]) (*connect.ServerStreamForClient[v1.PetStateResponse], error) {
	return c.watchPetState.CallServerStream(ctx, req)
}

// PetServiceHandler is an implementation of the hq.pet.v1.PetService service.
type PetServiceHandler interface {
	GetPetState(context.Context, *connect.Request[v1.GetPetStateRequest]) (*connect.Response[v1.PetStateResponse], error)
	FeedPet(context.Context, *connect.Request[v1.FeedPetRequest]) (*connect.Response[v1.PetStateResponse], error)
	PlayWithPet(context.Context, *connect.Request[v1.PlayWithPetRequest]) (*connect.Response[v1.PetStateResponse], error)
	ApplyGameResult(context.Context, *connect.Request[v1.ApplyGameResultRequest]) (*connect.Response[v1.PetStateResponse], error)
	PutPetToSleep(context.Context, *connect.Request[v1.PutPetToSleepRequest]) (*connect.Response[v1.PetStateResponse], error)
	WakePet(context.Context, *connect.Request[v1.WakePetRequest]) (*connect.Response[v1.PetStateResponse], error)
	WatchPetState(context.Context, *connect.Request[v1.WatchPetStateRequest], *connect.ServerStream[v1.PetStateResponse]) error
}

// NewPetServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPetServiceHandler(svc PetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	petServiceMethods := v1.File_hq_pet_v1_pet_proto.Services().ByName("PetService").Methods()
	petServiceGetPetStateHandler := connect.NewUnaryHandler(
		PetServiceGetPetStateProcedure,
		svc.GetPetState,
		connect.WithSchema(petServiceMethods.ByName("GetPetState")),
		connect.WithHandlerOptions(opts...),
	)
	petServiceFeedPetHandler := connect.NewUnaryHandler(
		PetServiceFeedPetProcedure,
		svc.FeedPet,
		connect.WithSchema(petServiceMethods.ByName("FeedPet")),
		connect.WithHandlerOptions(opts...),
	)
	petServicePlayWithPetHandler := connect.NewUnaryHandler(
		PetServicePlayWithPetProcedure,
		svc.PlayWithPet,
		connect.WithSchema(petServiceMethods.ByName("PlayWithPet")),
		connect.WithHandlerOptions(opts...),
	)
	petServiceApplyGameResultHandler := connect.NewUnaryHandler(
		PetServiceApplyGameResultProcedure,
		svc.ApplyGameResult,
		connect.WithSchema(petServiceMethods.ByName("ApplyGameResult")),
		connect.WithHandlerOptions(opts...),
	)
	petServicePutPetToSleepHandler := connect.NewUnaryHandler(
		PetServicePutPetToSleepProcedure,
		svc.PutPetToSleep,
		connect.WithSchema(petServiceMethods.ByName("PutPetToSleep")),
		connect.WithHandlerOptions(opts...),
	)
	petServiceWakePetHandler := connect.NewUnaryHandler(
		PetServiceWakePetProcedure,
		svc.WakePet,
		connect.WithSchema(petServiceMethods.ByName("WakePet")),
		connect.WithHandlerOptions(opts...),
	)
	petServiceWatchPetStateHandler := connect.NewServerStreamHandler(
		PetServiceWatchPetStateProcedure,
		svc.WatchPetState,
		connect.WithSchema(petServiceMethods.ByName("WatchPetState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/hq.pet.v1.PetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PetServiceGetPetStateProcedure:
			petServiceGetPetStateHandler.ServeHTTP(w, r)
		case PetServiceFeedPetProcedure:
			petServiceFeedPetHandler.ServeHTTP(w, r)
		case PetServicePlayWithPetProcedure:
			petServicePlayWithPetHandler.ServeHTTP(w, r)
		case PetServiceApplyGameResultProcedure:
			petServiceApplyGameResultHandler.ServeHTTP(w, r)
		case PetServicePutPetToSleepProcedure:
			petServicePutPetToSleepHandler.ServeHTTP(w, r)
		case PetServiceWakePetProcedure:
			petServiceWakePetHandler.ServeHTTP(w, r)
		case PetServiceWatchPetStateProcedure:
			petServiceWatchPetStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPetServiceHandler struct{}

func (UnimplementedPetServiceHandler) GetPetState(context.Context, *connect.Request[v1.GetPetStateRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.GetPetState is not implemented"))
}

func (UnimplementedPetServiceHandler) FeedPet(context.Context, *connect.Request[v1.FeedPetRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.FeedPet is not implemented"))
}

func (UnimplementedPetServiceHandler) PlayWithPet(context.Context, *connect.Request[v1.PlayWithPetRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.PlayWithPet is not implemented"))
}

func (UnimplementedPetServiceHandler) ApplyGameResult(context.Context, *connect.Request[v1.ApplyGameResultRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.ApplyGameResult is not implemented"))
}

func (UnimplementedPetServiceHandler) PutPetToSleep(context.Context, *connect.Request[v1.PutPetToSleepRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.PutPetToSleep is not implemented"))
}

func (UnimplementedPetServiceHandler) WakePet(context.Context, *connect.Request[v1.WakePetRequest]) (*connect.Response[v1.PetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.WakePet is not implemented"))
}

func (UnimplementedPetServiceHandler) WatchPetState(context.Context, *connect.Request[v1.WatchPetStateRequest], *connect.ServerStream[v1.PetStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hq.pet.v1.PetService.WatchPetState is not implemented"))
}
